PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
AllowUsers shipyard
DisableForwarding yes
AllowAgentForwarding no
AllowTcpForwarding no
GatewayPorts no
X11Forwarding no
PermitTunnel no
PermitUserEnvironment no
