"""GitHub Actions workflow generation.

Generates a .github/workflows/ci.yml from a Shipyard config,
supporting workflow_dispatch with runner_provider switching and
matrix builds across configured platforms.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from shipyard.core.config import Config

# Platform to runner mapping for each provider
_RUNNERS: dict[str, dict[str, str]] = {
    "github-hosted": {
        "macos": "macos-latest",
        "linux": "ubuntu-latest",
        "windows": "windows-latest",
    },
    "namespace": {
        "macos": "namespace-profile-macos-arm64",
        "linux": "namespace-profile-ubuntu-22.04-amd64",
        "windows": "namespace-profile-windows-2022-amd64",
    },
}

_DEFAULT_PROVIDER = "github-hosted"


def _runner_for(platform: str, provider: str) -> str:
    """Get the runner label for a platform and provider."""
    runners = _RUNNERS.get(provider, _RUNNERS[_DEFAULT_PROVIDER])
    return runners.get(platform, f"{platform}-latest")


def _indent(text: str, spaces: int) -> str:
    """Indent every line of text by the given number of spaces."""
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())


def generate_ci_workflow(config: Config) -> str:
    """Generate a GitHub Actions CI workflow YAML string.

    The generated workflow supports:
    - Push and pull_request triggers
    - workflow_dispatch with runner_provider input
    - Matrix strategy across configured platforms
    - Provider switching between github-hosted and namespace
    """
    platforms = config.platforms or ["macos", "linux"]
    project_name = config.project_name
    default_provider = config.cloud_provider

    # Build matrix includes
    includes_lines: list[str] = []
    for platform in platforms:
        gh_runner = _runner_for(platform, "github-hosted")
        ns_runner = _runner_for(platform, "namespace")
        includes_lines.append(
            f"          - platform: {platform}\n"
            f"            gh-runner: {gh_runner}\n"
            f"            ns-runner: {ns_runner}"
        )
    includes_block = "\n".join(includes_lines)

    # Build validation steps from config
    validation = config.validation.get("default", {})
    steps_lines: list[str] = []

    install_cmd = validation.get("install")
    if install_cmd:
        steps_lines.append(
            f"      - name: Install dependencies\n"
            f"        run: {install_cmd}"
        )

    build_cmd = validation.get("build")
    if build_cmd:
        steps_lines.append(
            f"      - name: Build\n"
            f"        run: {build_cmd}"
        )

    test_cmd = validation.get("test")
    if test_cmd:
        steps_lines.append(
            f"      - name: Test\n"
            f"        run: {test_cmd}"
        )

    validate_cmd = validation.get("validate")
    if validate_cmd:
        steps_lines.append(
            f"      - name: Validate\n"
            f"        run: {validate_cmd}"
        )

    # If no commands configured, add a placeholder
    if not steps_lines:
        steps_lines.append(
            "      - name: Build & Test\n"
            "        run: echo 'Configure validation commands in .shipyard/config.toml'"
        )

    steps_block = "\n\n".join(steps_lines)

    workflow = f"""\
# Generated by Shipyard — {project_name}
# https://github.com/danielraffel/shipyard

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      runner_provider:
        description: "Runner provider"
        required: false
        default: "{default_provider}"
        type: choice
        options:
          - github-hosted
          - namespace

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        include:
{includes_block}

    runs-on: >-
      ${{{{
        (github.event.inputs.runner_provider || '{default_provider}') == 'namespace'
        && matrix.ns-runner
        || matrix.gh-runner
      }}}}

    name: ${{{{ matrix.platform }}}}

    steps:
      - uses: actions/checkout@v4

{steps_block}
"""
    return workflow
